### ISSUE TITLE
Can not find the function run_forward_pass

### ISSUE THREAD

**Issue by firewood1996** [liecn/PyramidFL_mobicom22#2]
In this line, I cannot find the defination of the function '**run_forward_pass'**: https://github.com/liecn/PyramidFL/blob/527b73e0406a5af0b4b8f050990fc21c6720c505/training/learner.py#L550
Could you please tell me where is the defination?

**Comment by jinyucn** [comment]
Hello, do you solve this problem? I meet the same problem.

**Comment by liecn** [comment]
Hi,

For all cases used in PyramidFL, forward_pass is always False and run_forward_pass is not used. 

I also searched the [Oort repo](https://github.com/SymbioticLab/Oort) and no definition for this function. I suppose it is a legacy function and can be ignored.
