### ISSUE TITLE
Question about clientDataMap file

### ISSUE THREAD

**Issue by jinyucn** [liecn/PyramidFL_mobicom22#3]
Hello, I have a question about client map file in configuration as below.
- data_mapfile: /mnt/ufs18/nodr/home/lichenni/projects/FedScale/dataset/google_speech/clientDataMap

You have the clientDataMap file and use pickle to load it. However, in FedScale, they have train.csv in google_speech/client_data_mapping and use csv to read it. There is also a  'dis.pkl' file in their client_data_mapping directory.

Is 'dis.pkl' the same as clientDataMap? Or could you please provide the clientDataMap file. Thank you.

**Comment by liecn** [comment]
Hi,

Seems they refactored the code for fedscale. Attached please find the file you are asking for.

https://drive.google.com/drive/folders/1VwNmBQlhOcKo1_kUPvXdYNOZm3NQwWGL?usp=share_link

Best

**Comment by jinyucn** [comment]
Thank you very much. I also want to ask how to set args.learners, which is removed in FedScale. Is it the same meaning of executor? Or it's related to client number.

**Comment by liecn** [comment]
Learner is the number of launched processes, each of which can have multiple clients.

**Comment by jinyucn** [comment]
Ok, thank you!
