### ISSUE TITLE
For the openimage dataset, what is the `classTags` file?

### ISSUE THREAD

**Issue by li1553770945** [liecn/PyramidFL_mobicom22#4]
I am trying to reproduce this paper in the openimage dataset, but am getting the error `FileNotFoundError: [Errno 2] No such file or directory: 'xxx/dataset/data/openImg/classTags'` . I downloaded the dataset using the latest version of fedscale and I confirmed that there is no `classTags` folder. It's not clear to me if this is due to a mismatched version of the dataset

![image](https://github.com/liecn/PyramidFL/assets/55867654/f3c94851-a0c1-4b9a-8001-3bda5b09876d)

![image](https://github.com/liecn/PyramidFL/assets/55867654/65a173ab-ec7b-46bb-bb3b-18540f0d69ed)

**Comment by liecn** [comment]
Please download the file through this link. Thanks.
https://drive.google.com/file/d/1ngabu9gzipaSY9UJRYZd0BagMF2iokjV/view?usp=sharing

Fixed the access issue.

**Comment by li1553770945** [comment]
I noticed that for the google_speech dataset, the clientDataMap file changed, which you [replied and provided](https://github.com/liecn/PyramidFL/issues/3). For open_images dataset, I am experiencing the same issue, is it possible to provide the clientDataMap file for open_image dataset?

**Comment by liecn** [comment]
https://drive.google.com/file/d/12V6fp492mmWYRHAND_d_hWFa1JtLyant/view?usp=sharing
